#!/usr/bin/env bash
# Script to automate installation of nginx on a server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
