#!/usr/bin/env bash
# Script that configures nginx server to have a custom 404 page
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my404.html;
sudo service nginx start
