#!/usr/bin/env bash
# creates file, runs loop and deletes file
trap "echo I hate the kill command;clean_up" SIGTERM SIGQUIT
trap "echo Y U no love me?!;clean_up" SIGINT
function clean_up {

	# Perform program exit housekeeping
	rm /var/run/holbertonscript.pid
	exit
}

echo $$ >> /var/run/holbertonscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
done
