#!/usr/bin/env bash
#loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations
for (( i=1; i<=10; i=i+1 ));
do
    if (( i == 3 ));
    then
        echo "bad luck"
    elif (( i == 7 ));
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
done
