#!/usr/bin/env bash
for (( i=1; i<=10; i=i+1 ));
do
    if (( i == 3 ));
    then
        echo "bad luck"
    elif (( i == 7 ));
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
done
