#!/usr/bin/env bash
#displaying bad luck numbers
for ((i=1; i<=20; i++));
do
    case $i in
        4) echo "bad luck from China"
        ;;
        9) echo "bad luck from Japan"
        ;;
        17) echo "bad luck from Italy"
    esac
    echo $i
done
