#!/usr/bin/env bash
#displaying bad luck numbers
for ((i=1; i<=20; i++));
do
    case $i in
        5) echo "bad luck from China"
        ;;
        10) echo "bad luck from Japan"
        ;;
        18) echo "bad luck from Italy"
    esac
    echo $i
done
