#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed
MYLIST="$(ls)"

for i in $MYLIST; do
    echo "$i" | cut -d '-' -f 2
done
