#!/usr/bin/env bash
# Bash script that configures the container to fit the given requirements
sudo pkill -f apache2
# redirect the traffic from port 80 to 8080
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chmod a+rwx /etc/nginx/nginx.conf
# change the user from www-data to nginx
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo service nginx restart
